import torch
import sys

def print_keys(path):
    ckpt = torch.load(path, map_location='cpu')
    # 如果存的是整个模型
    if hasattr(ckpt, 'state_dict'):
        state = ckpt.state_dict()
    elif isinstance(ckpt, dict) and 'state_dict' in ckpt:
        state = ckpt['state_dict']
    else:
        state = ckpt

    for name, tensor in state.items():
        print(f"{name}  {list(tensor.shape)}")

if __name__ == '__main__':
    '''
    python check_ckpt.py UniTalker-B-D0-D7.pt UniTalker-L-D0-D7.pt
    '''
    for p in sys.argv[1:]:
        print(f"\n===== {p} =====")
        print_keys(p)


'''
===== UniTalker-B-D0-D7.pt =====
audio_encoder.masked_spec_embed  [768]
audio_encoder.feature_extractor.conv_layers.0.conv.weight  [512, 1, 10]
audio_encoder.feature_extractor.conv_layers.0.layer_norm.weight  [512]
audio_encoder.feature_extractor.conv_layers.0.layer_norm.bias  [512]
audio_encoder.feature_extractor.conv_layers.1.conv.weight  [512, 512, 3]
audio_encoder.feature_extractor.conv_layers.2.conv.weight  [512, 512, 3]
audio_encoder.feature_extractor.conv_layers.3.conv.weight  [512, 512, 3]
audio_encoder.feature_extractor.conv_layers.4.conv.weight  [512, 512, 3]
audio_encoder.feature_extractor.conv_layers.5.conv.weight  [512, 512, 2]
audio_encoder.feature_extractor.conv_layers.6.conv.weight  [512, 512, 2]
audio_encoder.feature_projection.layer_norm.weight  [512]
audio_encoder.feature_projection.layer_norm.bias  [512]
audio_encoder.feature_projection.projection.weight  [768, 512]
audio_encoder.feature_projection.projection.bias  [768]
audio_encoder.encoder.pos_conv_embed.conv.bias  [768]
audio_encoder.encoder.pos_conv_embed.conv.parametrizations.weight.original0  [1, 1, 128]
audio_encoder.encoder.pos_conv_embed.conv.parametrizations.weight.original1  [768, 48, 128]
audio_encoder.encoder.layer_norm.weight  [768]
audio_encoder.encoder.layer_norm.bias  [768]
audio_encoder.encoder.layers.0.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.0.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.0.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.0.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.0.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.0.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.0.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.0.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.0.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.0.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.0.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.0.attention.rel_attn_embed.weight  [320, 12]
audio_encoder.encoder.layers.0.layer_norm.weight  [768]
audio_encoder.encoder.layers.0.layer_norm.bias  [768]
audio_encoder.encoder.layers.0.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.0.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.0.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.0.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.0.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.0.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.1.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.1.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.1.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.1.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.1.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.1.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.1.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.1.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.1.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.1.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.1.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.1.layer_norm.weight  [768]
audio_encoder.encoder.layers.1.layer_norm.bias  [768]
audio_encoder.encoder.layers.1.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.1.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.1.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.1.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.1.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.1.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.2.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.2.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.2.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.2.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.2.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.2.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.2.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.2.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.2.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.2.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.2.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.2.layer_norm.weight  [768]
audio_encoder.encoder.layers.2.layer_norm.bias  [768]
audio_encoder.encoder.layers.2.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.2.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.2.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.2.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.2.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.2.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.3.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.3.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.3.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.3.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.3.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.3.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.3.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.3.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.3.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.3.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.3.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.3.layer_norm.weight  [768]
audio_encoder.encoder.layers.3.layer_norm.bias  [768]
audio_encoder.encoder.layers.3.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.3.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.3.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.3.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.3.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.3.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.4.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.4.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.4.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.4.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.4.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.4.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.4.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.4.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.4.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.4.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.4.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.4.layer_norm.weight  [768]
audio_encoder.encoder.layers.4.layer_norm.bias  [768]
audio_encoder.encoder.layers.4.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.4.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.4.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.4.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.4.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.4.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.5.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.5.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.5.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.5.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.5.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.5.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.5.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.5.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.5.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.5.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.5.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.5.layer_norm.weight  [768]
audio_encoder.encoder.layers.5.layer_norm.bias  [768]
audio_encoder.encoder.layers.5.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.5.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.5.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.5.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.5.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.5.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.6.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.6.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.6.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.6.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.6.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.6.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.6.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.6.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.6.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.6.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.6.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.6.layer_norm.weight  [768]
audio_encoder.encoder.layers.6.layer_norm.bias  [768]
audio_encoder.encoder.layers.6.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.6.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.6.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.6.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.6.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.6.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.7.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.7.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.7.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.7.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.7.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.7.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.7.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.7.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.7.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.7.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.7.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.7.layer_norm.weight  [768]
audio_encoder.encoder.layers.7.layer_norm.bias  [768]
audio_encoder.encoder.layers.7.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.7.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.7.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.7.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.7.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.7.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.8.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.8.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.8.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.8.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.8.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.8.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.8.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.8.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.8.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.8.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.8.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.8.layer_norm.weight  [768]
audio_encoder.encoder.layers.8.layer_norm.bias  [768]
audio_encoder.encoder.layers.8.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.8.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.8.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.8.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.8.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.8.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.9.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.9.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.9.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.9.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.9.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.9.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.9.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.9.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.9.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.9.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.9.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.9.layer_norm.weight  [768]
audio_encoder.encoder.layers.9.layer_norm.bias  [768]
audio_encoder.encoder.layers.9.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.9.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.9.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.9.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.9.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.9.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.10.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.10.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.10.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.10.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.10.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.10.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.10.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.10.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.10.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.10.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.10.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.10.layer_norm.weight  [768]
audio_encoder.encoder.layers.10.layer_norm.bias  [768]
audio_encoder.encoder.layers.10.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.10.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.10.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.10.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.10.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.10.final_layer_norm.bias  [768]
audio_encoder.encoder.layers.11.attention.gru_rel_pos_const  [1, 12, 1, 1]
audio_encoder.encoder.layers.11.attention.k_proj.weight  [768, 768]
audio_encoder.encoder.layers.11.attention.k_proj.bias  [768]
audio_encoder.encoder.layers.11.attention.v_proj.weight  [768, 768]
audio_encoder.encoder.layers.11.attention.v_proj.bias  [768]
audio_encoder.encoder.layers.11.attention.q_proj.weight  [768, 768]
audio_encoder.encoder.layers.11.attention.q_proj.bias  [768]
audio_encoder.encoder.layers.11.attention.out_proj.weight  [768, 768]
audio_encoder.encoder.layers.11.attention.out_proj.bias  [768]
audio_encoder.encoder.layers.11.attention.gru_rel_pos_linear.weight  [8, 64]
audio_encoder.encoder.layers.11.attention.gru_rel_pos_linear.bias  [8]
audio_encoder.encoder.layers.11.layer_norm.weight  [768]
audio_encoder.encoder.layers.11.layer_norm.bias  [768]
audio_encoder.encoder.layers.11.feed_forward.intermediate_dense.weight  [3072, 768]
audio_encoder.encoder.layers.11.feed_forward.intermediate_dense.bias  [3072]
audio_encoder.encoder.layers.11.feed_forward.output_dense.weight  [768, 3072]
audio_encoder.encoder.layers.11.feed_forward.output_dense.bias  [768]
audio_encoder.encoder.layers.11.final_layer_norm.weight  [768]
audio_encoder.encoder.layers.11.final_layer_norm.bias  [768]
decoder.learnable_style_emb.weight  [935, 64]
decoder.audio_feature_map.weight  [256, 768]
decoder.audio_feature_map.bias  [256]
decoder.tcn.first_net.conv_layers.0.residual_layer.0.weight  [256, 320, 3]
decoder.tcn.first_net.conv_layers.0.residual_layer.0.bias  [256]
decoder.tcn.first_net.conv_layers.0.conv.weight  [256, 320, 3]
decoder.tcn.first_net.conv_layers.0.conv.bias  [256]
decoder.tcn.first_net.conv_layers.0.norm.weight  [256]
decoder.tcn.first_net.conv_layers.0.norm.bias  [256]
decoder.tcn.first_net.conv_layers.1.conv.weight  [256, 256, 3]
decoder.tcn.first_net.conv_layers.1.conv.bias  [256]
decoder.tcn.first_net.conv_layers.1.norm.weight  [256]
decoder.tcn.first_net.conv_layers.1.norm.bias  [256]
decoder.tcn.first_net.conv_layers.2.conv.weight  [256, 256, 3]
decoder.tcn.first_net.conv_layers.2.conv.bias  [256]
decoder.tcn.first_net.conv_layers.2.norm.weight  [256]
decoder.tcn.first_net.conv_layers.2.norm.bias  [256]
out_head_dict.BIWI_23370_vertices.weight  [512, 256]
out_head_dict.BIWI_23370_vertices.bias  [512]
out_head_dict.FLAME_5023_vertices.weight  [512, 256]
out_head_dict.FLAME_5023_vertices.bias  [512]
out_head_dict.meshtalk_6172_vertices.weight  [512, 256]
out_head_dict.meshtalk_6172_vertices.bias  [512]
out_head_dict.3DETF_blendshape_weight.weight  [52, 256]
out_head_dict.3DETF_blendshape_weight.bias  [52]
out_head_dict.flame_params_from_dadhead.weight  [413, 256]
out_head_dict.flame_params_from_dadhead.bias  [413]
out_head_dict.inhouse_blendshape_weight.weight  [51, 256]
out_head_dict.inhouse_blendshape_weight.bias  [51]

===== UniTalker-L-D0-D7.pt =====
audio_encoder.masked_spec_embed  [1024]
audio_encoder.feature_extractor.conv_layers.0.conv.weight  [512, 1, 10]
audio_encoder.feature_extractor.conv_layers.0.conv.bias  [512]
audio_encoder.feature_extractor.conv_layers.0.layer_norm.weight  [512]
audio_encoder.feature_extractor.conv_layers.0.layer_norm.bias  [512]
audio_encoder.feature_extractor.conv_layers.1.conv.weight  [512, 512, 3]
audio_encoder.feature_extractor.conv_layers.1.conv.bias  [512]
audio_encoder.feature_extractor.conv_layers.1.layer_norm.weight  [512]
audio_encoder.feature_extractor.conv_layers.1.layer_norm.bias  [512]
audio_encoder.feature_extractor.conv_layers.2.conv.weight  [512, 512, 3]
audio_encoder.feature_extractor.conv_layers.2.conv.bias  [512]
audio_encoder.feature_extractor.conv_layers.2.layer_norm.weight  [512]
audio_encoder.feature_extractor.conv_layers.2.layer_norm.bias  [512]
audio_encoder.feature_extractor.conv_layers.3.conv.weight  [512, 512, 3]
audio_encoder.feature_extractor.conv_layers.3.conv.bias  [512]
audio_encoder.feature_extractor.conv_layers.3.layer_norm.weight  [512]
audio_encoder.feature_extractor.conv_layers.3.layer_norm.bias  [512]
audio_encoder.feature_extractor.conv_layers.4.conv.weight  [512, 512, 3]
audio_encoder.feature_extractor.conv_layers.4.conv.bias  [512]
audio_encoder.feature_extractor.conv_layers.4.layer_norm.weight  [512]
audio_encoder.feature_extractor.conv_layers.4.layer_norm.bias  [512]
audio_encoder.feature_extractor.conv_layers.5.conv.weight  [512, 512, 2]
audio_encoder.feature_extractor.conv_layers.5.conv.bias  [512]
audio_encoder.feature_extractor.conv_layers.5.layer_norm.weight  [512]
audio_encoder.feature_extractor.conv_layers.5.layer_norm.bias  [512]
audio_encoder.feature_extractor.conv_layers.6.conv.weight  [512, 512, 2]
audio_encoder.feature_extractor.conv_layers.6.conv.bias  [512]
audio_encoder.feature_extractor.conv_layers.6.layer_norm.weight  [512]
audio_encoder.feature_extractor.conv_layers.6.layer_norm.bias  [512]
audio_encoder.feature_projection.layer_norm.weight  [512]
audio_encoder.feature_projection.layer_norm.bias  [512]
audio_encoder.feature_projection.projection.weight  [1024, 512]
audio_encoder.feature_projection.projection.bias  [1024]
audio_encoder.encoder.pos_conv_embed.conv.bias  [1024]
audio_encoder.encoder.pos_conv_embed.conv.weight_g  [1, 1, 128]
audio_encoder.encoder.pos_conv_embed.conv.weight_v  [1024, 64, 128]
audio_encoder.encoder.layer_norm.weight  [1024]
audio_encoder.encoder.layer_norm.bias  [1024]
audio_encoder.encoder.layers.0.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.0.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.0.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.0.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.0.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.0.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.0.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.0.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.0.layer_norm.weight  [1024]
audio_encoder.encoder.layers.0.layer_norm.bias  [1024]
audio_encoder.encoder.layers.0.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.0.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.0.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.0.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.0.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.0.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.1.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.1.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.1.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.1.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.1.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.1.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.1.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.1.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.1.layer_norm.weight  [1024]
audio_encoder.encoder.layers.1.layer_norm.bias  [1024]
audio_encoder.encoder.layers.1.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.1.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.1.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.1.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.1.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.1.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.2.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.2.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.2.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.2.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.2.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.2.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.2.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.2.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.2.layer_norm.weight  [1024]
audio_encoder.encoder.layers.2.layer_norm.bias  [1024]
audio_encoder.encoder.layers.2.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.2.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.2.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.2.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.2.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.2.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.3.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.3.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.3.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.3.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.3.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.3.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.3.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.3.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.3.layer_norm.weight  [1024]
audio_encoder.encoder.layers.3.layer_norm.bias  [1024]
audio_encoder.encoder.layers.3.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.3.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.3.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.3.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.3.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.3.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.4.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.4.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.4.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.4.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.4.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.4.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.4.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.4.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.4.layer_norm.weight  [1024]
audio_encoder.encoder.layers.4.layer_norm.bias  [1024]
audio_encoder.encoder.layers.4.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.4.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.4.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.4.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.4.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.4.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.5.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.5.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.5.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.5.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.5.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.5.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.5.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.5.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.5.layer_norm.weight  [1024]
audio_encoder.encoder.layers.5.layer_norm.bias  [1024]
audio_encoder.encoder.layers.5.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.5.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.5.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.5.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.5.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.5.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.6.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.6.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.6.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.6.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.6.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.6.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.6.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.6.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.6.layer_norm.weight  [1024]
audio_encoder.encoder.layers.6.layer_norm.bias  [1024]
audio_encoder.encoder.layers.6.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.6.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.6.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.6.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.6.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.6.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.7.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.7.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.7.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.7.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.7.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.7.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.7.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.7.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.7.layer_norm.weight  [1024]
audio_encoder.encoder.layers.7.layer_norm.bias  [1024]
audio_encoder.encoder.layers.7.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.7.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.7.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.7.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.7.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.7.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.8.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.8.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.8.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.8.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.8.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.8.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.8.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.8.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.8.layer_norm.weight  [1024]
audio_encoder.encoder.layers.8.layer_norm.bias  [1024]
audio_encoder.encoder.layers.8.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.8.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.8.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.8.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.8.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.8.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.9.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.9.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.9.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.9.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.9.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.9.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.9.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.9.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.9.layer_norm.weight  [1024]
audio_encoder.encoder.layers.9.layer_norm.bias  [1024]
audio_encoder.encoder.layers.9.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.9.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.9.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.9.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.9.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.9.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.10.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.10.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.10.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.10.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.10.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.10.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.10.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.10.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.10.layer_norm.weight  [1024]
audio_encoder.encoder.layers.10.layer_norm.bias  [1024]
audio_encoder.encoder.layers.10.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.10.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.10.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.10.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.10.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.10.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.11.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.11.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.11.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.11.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.11.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.11.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.11.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.11.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.11.layer_norm.weight  [1024]
audio_encoder.encoder.layers.11.layer_norm.bias  [1024]
audio_encoder.encoder.layers.11.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.11.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.11.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.11.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.11.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.11.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.12.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.12.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.12.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.12.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.12.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.12.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.12.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.12.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.12.layer_norm.weight  [1024]
audio_encoder.encoder.layers.12.layer_norm.bias  [1024]
audio_encoder.encoder.layers.12.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.12.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.12.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.12.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.12.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.12.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.13.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.13.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.13.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.13.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.13.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.13.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.13.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.13.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.13.layer_norm.weight  [1024]
audio_encoder.encoder.layers.13.layer_norm.bias  [1024]
audio_encoder.encoder.layers.13.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.13.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.13.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.13.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.13.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.13.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.14.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.14.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.14.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.14.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.14.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.14.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.14.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.14.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.14.layer_norm.weight  [1024]
audio_encoder.encoder.layers.14.layer_norm.bias  [1024]
audio_encoder.encoder.layers.14.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.14.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.14.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.14.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.14.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.14.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.15.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.15.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.15.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.15.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.15.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.15.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.15.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.15.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.15.layer_norm.weight  [1024]
audio_encoder.encoder.layers.15.layer_norm.bias  [1024]
audio_encoder.encoder.layers.15.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.15.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.15.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.15.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.15.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.15.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.16.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.16.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.16.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.16.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.16.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.16.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.16.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.16.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.16.layer_norm.weight  [1024]
audio_encoder.encoder.layers.16.layer_norm.bias  [1024]
audio_encoder.encoder.layers.16.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.16.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.16.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.16.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.16.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.16.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.17.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.17.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.17.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.17.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.17.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.17.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.17.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.17.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.17.layer_norm.weight  [1024]
audio_encoder.encoder.layers.17.layer_norm.bias  [1024]
audio_encoder.encoder.layers.17.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.17.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.17.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.17.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.17.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.17.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.18.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.18.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.18.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.18.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.18.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.18.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.18.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.18.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.18.layer_norm.weight  [1024]
audio_encoder.encoder.layers.18.layer_norm.bias  [1024]
audio_encoder.encoder.layers.18.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.18.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.18.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.18.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.18.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.18.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.19.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.19.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.19.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.19.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.19.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.19.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.19.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.19.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.19.layer_norm.weight  [1024]
audio_encoder.encoder.layers.19.layer_norm.bias  [1024]
audio_encoder.encoder.layers.19.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.19.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.19.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.19.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.19.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.19.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.20.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.20.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.20.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.20.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.20.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.20.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.20.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.20.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.20.layer_norm.weight  [1024]
audio_encoder.encoder.layers.20.layer_norm.bias  [1024]
audio_encoder.encoder.layers.20.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.20.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.20.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.20.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.20.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.20.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.21.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.21.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.21.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.21.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.21.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.21.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.21.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.21.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.21.layer_norm.weight  [1024]
audio_encoder.encoder.layers.21.layer_norm.bias  [1024]
audio_encoder.encoder.layers.21.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.21.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.21.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.21.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.21.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.21.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.22.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.22.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.22.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.22.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.22.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.22.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.22.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.22.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.22.layer_norm.weight  [1024]
audio_encoder.encoder.layers.22.layer_norm.bias  [1024]
audio_encoder.encoder.layers.22.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.22.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.22.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.22.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.22.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.22.final_layer_norm.bias  [1024]
audio_encoder.encoder.layers.23.attention.k_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.23.attention.k_proj.bias  [1024]
audio_encoder.encoder.layers.23.attention.v_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.23.attention.v_proj.bias  [1024]
audio_encoder.encoder.layers.23.attention.q_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.23.attention.q_proj.bias  [1024]
audio_encoder.encoder.layers.23.attention.out_proj.weight  [1024, 1024]
audio_encoder.encoder.layers.23.attention.out_proj.bias  [1024]
audio_encoder.encoder.layers.23.layer_norm.weight  [1024]
audio_encoder.encoder.layers.23.layer_norm.bias  [1024]
audio_encoder.encoder.layers.23.feed_forward.intermediate_dense.weight  [4096, 1024]
audio_encoder.encoder.layers.23.feed_forward.intermediate_dense.bias  [4096]
audio_encoder.encoder.layers.23.feed_forward.output_dense.weight  [1024, 4096]
audio_encoder.encoder.layers.23.feed_forward.output_dense.bias  [1024]
audio_encoder.encoder.layers.23.final_layer_norm.weight  [1024]
audio_encoder.encoder.layers.23.final_layer_norm.bias  [1024]
decoder.learnable_style_emb.weight  [935, 64]
decoder.audio_feature_map.weight  [256, 1024]
decoder.audio_feature_map.bias  [256]
decoder.tcn.first_net.conv_layers.0.residual_layer.0.weight  [256, 320, 3]
decoder.tcn.first_net.conv_layers.0.residual_layer.0.bias  [256]
decoder.tcn.first_net.conv_layers.0.conv.weight  [256, 320, 3]
decoder.tcn.first_net.conv_layers.0.conv.bias  [256]
decoder.tcn.first_net.conv_layers.0.norm.weight  [256]
decoder.tcn.first_net.conv_layers.0.norm.bias  [256]
decoder.tcn.first_net.conv_layers.1.conv.weight  [256, 256, 3]
decoder.tcn.first_net.conv_layers.1.conv.bias  [256]
decoder.tcn.first_net.conv_layers.1.norm.weight  [256]
decoder.tcn.first_net.conv_layers.1.norm.bias  [256]
decoder.tcn.first_net.conv_layers.2.conv.weight  [256, 256, 3]
decoder.tcn.first_net.conv_layers.2.conv.bias  [256]
decoder.tcn.first_net.conv_layers.2.norm.weight  [256]
decoder.tcn.first_net.conv_layers.2.norm.bias  [256]
out_head_dict.3DETF_blendshape_weight.weight  [52, 256]
out_head_dict.3DETF_blendshape_weight.bias  [52]
out_head_dict.FLAME_5023_vertices.weight  [512, 256]
out_head_dict.FLAME_5023_vertices.bias  [512]
out_head_dict.BIWI_23370_vertices.weight  [512, 256]
out_head_dict.BIWI_23370_vertices.bias  [512]
out_head_dict.flame_params_from_dadhead.weight  [413, 256]
out_head_dict.flame_params_from_dadhead.bias  [413]
out_head_dict.inhouse_blendshape_weight.weight  [51, 256]
out_head_dict.inhouse_blendshape_weight.bias  [51]
out_head_dict.meshtalk_6172_vertices.weight  [512, 256]
out_head_dict.meshtalk_6172_vertices.bias  [512]
'''